package d14

type problem struct {
	template string
	rules    map[pair]byte
}

// Little helper.
func p(s string) pair {
	return pair{s[0], s[1]}
}

var (
	exampleInput = problem{
		template: "NNCB",
		rules: map[pair]byte{
			p("CH"): 'B',
			p("HH"): 'N',
			p("CB"): 'H',
			p("NH"): 'C',
			p("HB"): 'C',
			p("HC"): 'B',
			p("HN"): 'C',
			p("NN"): 'C',
			p("BH"): 'H',
			p("NC"): 'B',
			p("NB"): 'B',
			p("BN"): 'B',
			p("BB"): 'N',
			p("BC"): 'B',
			p("CC"): 'N',
			p("CN"): 'C',
		},
	}

	realInput = problem{
		template: "VOKKVSKKPSBVOOKVCFOV",
		rules: map[pair]byte{
			p("PK"): 'P',
			p("BB"): 'V',
			p("SO"): 'O',
			p("OO"): 'V',
			p("PV"): 'O',
			p("CB"): 'H',
			p("FH"): 'F',
			p("SC"): 'F',
			p("KF"): 'C',
			p("VS"): 'O',
			p("VP"): 'V',
			p("FS"): 'K',
			p("SP"): 'C',
			p("FC"): 'N',
			p("CF"): 'C',
			p("BF"): 'V',
			p("FN"): 'K',
			p("NH"): 'F',
			p("OB"): 'F',
			p("SV"): 'H',
			p("BN"): 'N',
			p("OK"): 'K',
			p("NF"): 'S',
			p("OH"): 'S',
			p("FV"): 'B',
			p("OC"): 'F',
			p("VF"): 'V',
			p("HO"): 'H',
			p("PS"): 'N',
			p("NB"): 'N',
			p("NS"): 'B',
			p("OS"): 'P',
			p("CS"): 'S',
			p("CH"): 'N',
			p("PC"): 'N',
			p("BH"): 'F',
			p("HP"): 'P',
			p("HH"): 'V',
			p("BK"): 'H',
			p("HC"): 'B',
			p("NK"): 'S',
			p("SB"): 'C',
			p("NO"): 'K',
			p("SN"): 'H',
			p("VV"): 'N',
			p("ON"): 'P',
			p("VN"): 'H',
			p("VB"): 'P',
			p("BV"): 'O',
			p("CV"): 'N',
			p("HV"): 'C',
			p("SH"): 'C',
			p("KV"): 'F',
			p("BC"): 'O',
			p("OF"): 'P',
			p("NN"): 'C',
			p("KN"): 'F',
			p("CO"): 'C',
			p("HN"): 'P',
			p("PP"): 'V',
			p("FP"): 'O',
			p("CP"): 'S',
			p("FB"): 'F',
			p("CN"): 'S',
			p("VC"): 'C',
			p("PF"): 'F',
			p("PO"): 'B',
			p("KB"): 'H',
			p("HF"): 'P',
			p("SK"): 'P',
			p("SF"): 'H',
			p("VO"): 'N',
			p("HK"): 'C',
			p("HB"): 'C',
			p("OP"): 'B',
			p("SS"): 'V',
			p("NV"): 'O',
			p("KS"): 'N',
			p("PH"): 'H',
			p("KK"): 'B',
			p("HS"): 'S',
			p("PN"): 'F',
			p("OV"): 'S',
			p("PB"): 'S',
			p("NC"): 'B',
			p("BS"): 'N',
			p("KP"): 'C',
			p("FO"): 'B',
			p("FK"): 'N',
			p("BP"): 'C',
			p("NP"): 'C',
			p("KO"): 'C',
			p("VK"): 'K',
			p("FF"): 'C',
			p("VH"): 'H',
			p("CC"): 'F',
			p("BO"): 'S',
			p("KH"): 'B',
			p("CK"): 'K',
			p("KC"): 'C',
		},
	}
)
